"""
utils/itinerary_formatter.py
-----------------------------
Utilities for formatting and exporting itineraries.
"""

from __future__ import annotations

import json
from datetime import datetime
from typing import Any

from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.text import Text

console = Console()


def format_itinerary_markdown(itinerary: dict[str, Any]) -> str:
    """Convert structured itinerary dict to markdown string."""
    lines = []
    dest = itinerary.get("destination", "Unknown")
    dates = itinerary.get("dates", {})
    travelers = itinerary.get("travelers", 1)
    budget = itinerary.get("budget", {})

    lines.append(f"# ✈️ {dest} Travel Itinerary\n")
    lines.append(
        f"**{dates.get('departure', '')} → {dates.get('return', '')}** | "
        f"{dates.get('duration_days', 0)} days | "
        f"{travelers} traveler(s) | "
        f"Budget: ${budget.get('total_usd', 0):,.0f}\n"
    )

    # Flights section
    flight = itinerary.get("flight")
    if flight:
        lines.append("## ✈️ Flights\n")
        lines.append(f"**{flight['airline']}** | {flight['origin']} → {flight['destination']}")
        lines.append(f"- Departure: {flight['departure_time']}")
        lines.append(f"- Duration: {flight['duration_minutes'] // 60}h {flight['duration_minutes'] % 60}m")
        lines.append(f"- Stops: {flight['stops']} | Class: {flight['cabin_class'].title()}")
        lines.append(f"- Cost: **${flight['price_usd']:,.2f}**\n")

    # Hotel section
    hotel = itinerary.get("hotel")
    if hotel:
        lines.append("## 🏨 Accommodation\n")
        lines.append(f"**{hotel['name']}** {'⭐' * int(hotel['stars'])}")
        lines.append(f"- Location: {hotel['location']}")
        lines.append(f"- Check-in: {hotel['check_in']} | Check-out: {hotel['check_out']}")
        lines.append(f"- Rate: ${hotel['price_per_night_usd']:.0f}/night | Total: **${hotel['total_price_usd']:,.2f}**")
        if hotel.get("amenities"):
            lines.append(f"- Amenities: {', '.join(hotel['amenities'][:6])}\n")

    # Activities section
    activities = itinerary.get("activities", [])
    if activities:
        lines.append("## 📅 Day-by-Day Schedule\n")
        day_groups: dict[int, list] = {}
        for act in activities:
            day = act.get("day_number", 1)
            day_groups.setdefault(day, []).append(act)

        time_order = {"morning": 0, "afternoon": 1, "evening": 2, "flexible": 3}
        for day_num in sorted(day_groups.keys()):
            day_acts = sorted(day_groups[day_num], key=lambda x: time_order.get(x.get("time_of_day", "flexible"), 3))
            lines.append(f"### Day {day_num}\n")
            for act in day_acts:
                time = act.get("time_of_day", "").title()
                name = act.get("name", "")
                duration = act.get("duration_hours", 0)
                price = act.get("price_usd", 0)
                lines.append(f"- **{time}** — {name}")
                lines.append(f"  _{duration:.0f} hours | ${price:.0f}_\n")

    # Budget summary
    lines.append("## 💰 Budget Summary\n")
    breakdown = budget.get("breakdown", {})
    lines.append("| Category | Amount |")
    lines.append("|----------|--------|")
    lines.append(f"| ✈️ Flights | ${breakdown.get('flights', 0):,.2f} |")
    lines.append(f"| 🏨 Hotels | ${breakdown.get('hotels', 0):,.2f} |")
    lines.append(f"| 🎯 Activities | ${breakdown.get('activities', 0):,.2f} |")
    lines.append(f"| **Total** | **${budget.get('spent_usd', 0):,.2f}** |")
    lines.append(f"| Remaining | ${budget.get('remaining_usd', 0):,.2f} |")
    utilization = budget.get("utilization_percent", 0)
    lines.append(f"\n_Budget utilization: {utilization:.0f}%_\n")

    lines.append("---\n")
    lines.append("_Generated by Multi-Agent Travel Planner — LangGraph · CrewAI · AutoGen · PydanticAI_")

    return "\n".join(lines)


def print_itinerary_summary(itinerary: dict[str, Any]) -> None:
    """Print a rich-formatted summary to the terminal."""
    dest = itinerary.get("destination", "Unknown")
    budget = itinerary.get("budget", {})
    activities = itinerary.get("activities", [])

    table = Table(title=f"📋 {dest} — Trip Summary", show_header=True, header_style="bold blue")
    table.add_column("Component", style="cyan", width=20)
    table.add_column("Details", width=40)
    table.add_column("Cost (USD)", justify="right", style="green")

    flight = itinerary.get("flight")
    if flight:
        table.add_row(
            "✈️  Flight",
            f"{flight['airline']}: {flight['origin']}→{flight['destination']}, {flight['stops']} stop(s)",
            f"${flight['price_usd']:,.0f}",
        )

    hotel = itinerary.get("hotel")
    if hotel:
        table.add_row(
            "🏨 Hotel",
            f"{hotel['name']} ({hotel['stars']}★), {hotel['location']}",
            f"${hotel['total_price_usd']:,.0f}",
        )

    if activities:
        total_act_cost = sum(a.get("price_usd", 0) for a in activities)
        table.add_row(
            "🎯 Activities",
            f"{len(activities)} experiences planned",
            f"${total_act_cost:,.0f}",
        )

    table.add_section()
    table.add_row(
        "[bold]TOTAL[/bold]",
        f"{budget.get('utilization_percent', 0):.0f}% of ${budget.get('total_usd', 0):,.0f} budget",
        f"[bold]${budget.get('spent_usd', 0):,.0f}[/bold]",
    )

    console.print(table)


def save_itinerary_json(itinerary: dict[str, Any], filepath: str) -> None:
    """Save itinerary as JSON file."""
    with open(filepath, "w") as f:
        json.dump(itinerary, f, indent=2, default=str)
    console.print(f"[dim]💾 Itinerary JSON saved: {filepath}[/dim]")
